// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// NOTE:
// - We intentionally do NOT use the generated `Database` types here because this repo cannot update
//   `src/integrations/supabase/types.ts` (read-only in Lovable), which would otherwise cause
//   `supabase.from('...')` to be typed as `never` for new tables.
// - Supabase anon key is public by design (safe to ship in frontend).

const SUPABASE_URL = 'https://lqduauyrwwlrbtnxkiev.supabase.co';
const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZHVhdXlyd3dscmJ0bnhraWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2MjQ0NzYsImV4cCI6MjA4MzIwMDQ3Nn0.Xe0_Jd3NgckKBI7T9jszUXwIY0YtCbzWOLU00EBpQHA';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});