// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agndhravgmcwpdjkozka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnbmRocmF2Z21jd3BkamtvemthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NDMzOTksImV4cCI6MjA3MjUxOTM5OX0.B8m5QFl6QGEhsCTGZf2WDWaVcv5765oVrkZXqPJhB9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});